### ISSUE TITLE
Get new episodes through manual button

### ISSUE THREAD

**Issue by jward8** [jward8/small-town-murder-map#5]
As stated in one of the comments of issue #1 , the current approach to getting new episodes will be going and clicking a button manually to retrieve new episode data.

**Roadmap**

- [x] Add logic in front end to click new button
- [x] Gather number of current episodes and send to server
- [x] Using number sent to server, go through feed and get information for new episodes up to most recent in database
- [x] Send data back and save to Firestore
- [x] Reload map to plot new points
